# Generated by Django 4.0.6 on 2022-07-18 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('released_date', models.DateField(default=django.utils.timezone.now)),
                ('length_time', models.CharField(max_length=3)),
                ('description', models.TextField()),
                ('trail_link', models.URLField()),
                ('movies_image', models.ImageField(upload_to='')),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
